const challenges = [
  // ===== BASIC (1-10) =====
  {
    id: 1,
    difficulty: 'basic',
    title: 'सभी Employees देखो',
    question: 'employees table से सारा data दिखाओ।',
    hint: 'SELECT * use करो',
    expectedQuery: 'SELECT * FROM employees',
  },
  {
    id: 2,
    difficulty: 'basic',
    title: 'सिर्फ Name और Salary',
    question: 'employees table से सिर्फ name और salary columns दिखाओ।',
    hint: 'Specific columns select करो',
    expectedQuery: 'SELECT name, salary FROM employees',
  },
  {
    id: 3,
    difficulty: 'basic',
    title: 'Mumbai के Employees',
    question: 'सिर्फ वो employees दिखाओ जो Mumbai में रहते हैं।',
    hint: 'WHERE clause use करो with city',
    expectedQuery: "SELECT * FROM employees WHERE city = 'Mumbai'",
  },
  {
    id: 4,
    difficulty: 'basic',
    title: 'महंगे Products',
    question: 'वो products दिखाओ जिनकी price 5000 से ज़्यादा है।',
    hint: 'WHERE clause with > operator',
    expectedQuery: 'SELECT * FROM products WHERE price > 5000',
  },
  {
    id: 5,
    difficulty: 'basic',
    title: 'Unique Cities',
    question: 'employees table में कितनी अलग-अलग cities हैं? सब unique cities दिखाओ।',
    hint: 'DISTINCT keyword use करो',
    expectedQuery: 'SELECT DISTINCT city FROM employees',
  },
  {
    id: 6,
    difficulty: 'basic',
    title: 'Salary से Sort करो',
    question: 'सारे employees को salary के हिसाब से highest से lowest sort करके दिखाओ (name और salary दिखाओ)।',
    hint: 'ORDER BY ... DESC use करो',
    expectedQuery: 'SELECT name, salary FROM employees ORDER BY salary DESC',
  },
  {
    id: 7,
    difficulty: 'basic',
    title: 'Total Customers Count',
    question: 'customers table में कुल कितने customers हैं?',
    hint: 'COUNT(*) aggregate function use करो',
    expectedQuery: 'SELECT COUNT(*) AS total_customers FROM customers',
  },
  {
    id: 8,
    difficulty: 'basic',
    title: 'Pending Orders',
    question: 'वो orders दिखाओ जिनका status "pending" है।',
    hint: "WHERE status = 'pending'",
    expectedQuery: "SELECT * FROM orders WHERE status = 'pending'",
  },
  {
    id: 9,
    difficulty: 'basic',
    title: 'Mumbai या Delhi वाले',
    question: 'वो employees दिखाओ जो Mumbai या Delhi में रहते हैं।',
    hint: 'IN operator या OR use करो',
    expectedQuery: "SELECT * FROM employees WHERE city IN ('Mumbai', 'Delhi')",
  },
  {
    id: 10,
    difficulty: 'basic',
    title: 'Top 5 Salary',
    question: 'सबसे ज़्यादा salary वाले top 5 employees दिखाओ (name, salary)।',
    hint: 'ORDER BY + LIMIT use करो',
    expectedQuery: 'SELECT name, salary FROM employees ORDER BY salary DESC LIMIT 5',
  },

  // ===== INTERMEDIATE (11-20) =====
  {
    id: 11,
    difficulty: 'intermediate',
    title: 'Employee + Department (INNER JOIN)',
    question: 'हर employee का name और उसका department name दिखाओ। (सिर्फ वो जिनका department है)',
    hint: 'INNER JOIN departments ON department_id',
    expectedQuery: 'SELECT e.name, d.name AS department FROM employees e INNER JOIN departments d ON e.department_id = d.id',
  },
  {
    id: 12,
    difficulty: 'intermediate',
    title: 'सब Employees — Department हो या ना हो (LEFT JOIN)',
    question: 'सारे employees दिखाओ उनके department name के साथ। जिसका department नहीं है उसका भी दिखना चाहिए (NULL आएगा)।',
    hint: 'LEFT JOIN use करो — LEFT side (employees) के सारे rows आएंगे',
    expectedQuery: 'SELECT e.name, d.name AS department FROM employees e LEFT JOIN departments d ON e.department_id = d.id',
  },
  {
    id: 13,
    difficulty: 'intermediate',
    title: 'City-wise Employee Count (GROUP BY)',
    question: 'हर city में कितने employees हैं? City और count दिखाओ, count के हिसाब से sort करो।',
    hint: 'GROUP BY city + COUNT(*) + ORDER BY',
    expectedQuery: 'SELECT city, COUNT(*) AS emp_count FROM employees GROUP BY city ORDER BY emp_count DESC',
  },
  {
    id: 14,
    difficulty: 'intermediate',
    title: 'Department Average Salary',
    question: 'हर department की average salary दिखाओ (department name और avg salary)।',
    hint: 'JOIN + GROUP BY + AVG()',
    expectedQuery: 'SELECT d.name AS department, ROUND(AVG(e.salary), 2) AS avg_salary FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.name',
  },
  {
    id: 15,
    difficulty: 'intermediate',
    title: 'Customer Total Spend',
    question: 'हर customer ने कुल कितना खर्चा किया? Customer name और total amount दिखाओ, highest spend पहले।',
    hint: 'JOIN customers + orders + SUM(total_amount) + GROUP BY',
    expectedQuery: 'SELECT c.name, SUM(o.total_amount) AS total_spent FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id ORDER BY total_spent DESC',
  },
  {
    id: 16,
    difficulty: 'intermediate',
    title: 'HAVING — बड़ी Cities',
    question: 'वो cities दिखाओ जहाँ 3 या उससे ज़्यादा employees हैं।',
    hint: 'GROUP BY + HAVING COUNT(*) >= 3',
    expectedQuery: 'SELECT city, COUNT(*) AS emp_count FROM employees GROUP BY city HAVING COUNT(*) >= 3',
  },
  {
    id: 17,
    difficulty: 'intermediate',
    title: 'Category-wise Product Stats',
    question: 'हर product category में कितने products हैं, average price क्या है, और total stock कितना है?',
    hint: 'GROUP BY category + COUNT, AVG, SUM',
    expectedQuery: 'SELECT category, COUNT(*) AS total_products, ROUND(AVG(price), 2) AS avg_price, SUM(stock) AS total_stock FROM products GROUP BY category',
  },
  {
    id: 18,
    difficulty: 'intermediate',
    title: 'Student Toppers',
    question: 'हर student का name, class, और total marks (तीनों subjects का) दिखाओ। Total marks के हिसाब से sort करो।',
    hint: 'JOIN students + marks + SUM(score) + GROUP BY + ORDER BY',
    expectedQuery: 'SELECT s.name, s.class, SUM(m.score) AS total_marks FROM students s JOIN marks m ON s.id = m.student_id GROUP BY s.id ORDER BY total_marks DESC',
  },
  {
    id: 19,
    difficulty: 'intermediate',
    title: 'Orders Between Dates',
    question: 'January 2024 से March 2024 के बीच जो orders delivered हुए, उनका customer name, product name, और amount दिखाओ।',
    hint: 'Multiple JOINs + WHERE with BETWEEN and status',
    expectedQuery: "SELECT c.name AS customer, p.name AS product, o.total_amount FROM orders o JOIN customers c ON o.customer_id = c.id JOIN products p ON o.product_id = p.id WHERE o.order_date BETWEEN '2024-01-01' AND '2024-03-31' AND o.status = 'delivered'",
  },
  {
    id: 20,
    difficulty: 'intermediate',
    title: 'Indian Customers — City-wise Orders',
    question: 'India के customers में से हर city से कितने orders आए? City और order count दिखाओ।',
    hint: "JOIN customers + orders + WHERE country = 'India' + GROUP BY city",
    expectedQuery: "SELECT c.city, COUNT(o.id) AS order_count FROM customers c JOIN orders o ON c.id = o.customer_id WHERE c.country = 'India' GROUP BY c.city ORDER BY order_count DESC",
  },

  // ===== ADVANCED (21-30) =====
  {
    id: 21,
    difficulty: 'advanced',
    title: 'Average से ज़्यादा Salary (Subquery)',
    question: 'वो employees दिखाओ जिनकी salary average salary से ज़्यादा है (name, salary, city)।',
    hint: 'WHERE salary > (SELECT AVG(salary) FROM employees)',
    expectedQuery: 'SELECT name, salary, city FROM employees WHERE salary > (SELECT AVG(salary) FROM employees) ORDER BY salary DESC',
  },
  {
    id: 22,
    difficulty: 'advanced',
    title: '2nd Highest Salary',
    question: 'दूसरी सबसे ज़्यादा salary कितनी है और किसकी है?',
    hint: 'ORDER BY salary DESC + LIMIT 1 OFFSET 1',
    expectedQuery: 'SELECT name, salary FROM employees ORDER BY salary DESC LIMIT 1 OFFSET 1',
  },
  {
    id: 23,
    difficulty: 'advanced',
    title: 'Employee + Manager Name (Self JOIN)',
    question: 'हर employee का name और उसके manager का name दिखाओ। जिसका manager नहीं है उसके लिए NULL आए।',
    hint: 'Self LEFT JOIN — employees table को खुद से join करो manager_id पर',
    expectedQuery: 'SELECT e.name AS employee, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id',
  },
  {
    id: 24,
    difficulty: 'advanced',
    title: 'Department — ज़्यादा Average Salary वाले (HAVING + JOIN)',
    question: 'वो departments दिखाओ जिनकी average salary 90000 से ज़्यादा है। Department name और average salary दिखाओ।',
    hint: 'JOIN + GROUP BY + HAVING AVG(salary) > 90000',
    expectedQuery: 'SELECT d.name AS department, ROUND(AVG(e.salary), 2) AS avg_salary FROM employees e JOIN departments d ON e.department_id = d.id GROUP BY d.name HAVING AVG(e.salary) > 90000',
  },
  {
    id: 25,
    difficulty: 'advanced',
    title: '80+ Average वाले Students (HAVING)',
    question: 'वो students दिखाओ जिनका average score 80 से ज़्यादा है। Name, class, और average score दिखाओ।',
    hint: 'JOIN + GROUP BY + HAVING AVG(score) > 80',
    expectedQuery: 'SELECT s.name, s.class, ROUND(AVG(m.score), 2) AS avg_score FROM students s JOIN marks m ON s.id = m.student_id GROUP BY s.id HAVING AVG(m.score) > 80 ORDER BY avg_score DESC',
  },
  {
    id: 26,
    difficulty: 'advanced',
    title: 'Product — कभी Order नहीं हुआ (LEFT JOIN + NULL)',
    question: 'वो products दिखाओ जिनका कभी कोई order नहीं आया।',
    hint: 'LEFT JOIN orders + WHERE order.id IS NULL',
    expectedQuery: 'SELECT p.name, p.category, p.price FROM products p LEFT JOIN orders o ON p.id = o.product_id WHERE o.id IS NULL',
  },
  {
    id: 27,
    difficulty: 'advanced',
    title: 'Department में सबसे ज़्यादा Salary (Correlated Subquery)',
    question: 'हर department में सबसे ज़्यादा salary किसकी है? Employee name, department name, और salary दिखाओ।',
    hint: 'Correlated subquery — WHERE salary = (SELECT MAX(salary) ... WHERE department_id = outer department_id)',
    expectedQuery: 'SELECT e.name, d.name AS department, e.salary FROM employees e JOIN departments d ON e.department_id = d.id WHERE e.salary = (SELECT MAX(e2.salary) FROM employees e2 WHERE e2.department_id = e.department_id)',
  },
  {
    id: 28,
    difficulty: 'advanced',
    title: 'Salary Grade (CASE WHEN)',
    question: 'हर employee का name, salary, और grade दिखाओ: 100000+ = "Senior", 70000-99999 = "Mid", बाकी = "Junior"।',
    hint: 'CASE WHEN ... THEN ... END use करो',
    expectedQuery: "SELECT name, salary, CASE WHEN salary >= 100000 THEN 'Senior' WHEN salary >= 70000 THEN 'Mid' ELSE 'Junior' END AS grade FROM employees ORDER BY salary DESC",
  },
  {
    id: 29,
    difficulty: 'advanced',
    title: 'Subject Topper (हर Subject में Top)',
    question: 'हर subject में सबसे ज़्यादा marks किसके हैं? Subject, student name, और score दिखाओ।',
    hint: 'Correlated subquery या GROUP BY + MAX approach',
    expectedQuery: 'SELECT m.subject, s.name, m.score FROM marks m JOIN students s ON m.student_id = s.id WHERE m.score = (SELECT MAX(m2.score) FROM marks m2 WHERE m2.subject = m.subject)',
  },
  {
    id: 30,
    difficulty: 'advanced',
    title: 'Full Report — Customer + Orders + Products (Triple JOIN)',
    question: 'हर customer का name, city, उन्होंने कितने orders दिए, कितने unique products खरीदे, और total कितना खर्चा किया — सब एक query में दिखाओ। Total spend से sort करो।',
    hint: 'Multiple JOINs + COUNT, COUNT(DISTINCT ...), SUM + GROUP BY',
    expectedQuery: 'SELECT c.name, c.city, COUNT(o.id) AS total_orders, COUNT(DISTINCT o.product_id) AS unique_products, SUM(o.total_amount) AS total_spent FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id ORDER BY total_spent DESC',
  },
];

export function getAllChallenges() {
  return challenges.map(({ id, difficulty, title, question, hint }) => ({
    id, difficulty, title, question, hint,
  }));
}

export function getChallengeById(id) {
  return challenges.find(c => c.id === id) || null;
}
